services:

  express-app:
    # build: .
    image: auraf285/release-nodejs:latest
    ports: 
      - "8080:8080" # host:container
    restart: always

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Check for new images every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower